version: '3'

services:

  mysql:
    image: mysql:8.0.33
    container_name: db
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-initdb.d:/docker-entrypoint-initdb.d

volumes:
  mysql-data:
  